sudo: required
language: python
addons:
  apt:
    packages:
    - libusb-1.0-0-dev
    - libudev-dev
matrix:
  include:
  - if: tag =~ .+
    os: osx
    language: ruby
    osx_image: xcode7.3
  - os: linux
    python: "3.4"
    services:
    - docker
  - if: NOT tag =~ .+
    os: linux
    python: "3.5"
  - if: NOT tag =~ .+
    os: linux
    python: "3.6"
before_install:
- source contrib/zclassic/travis/electrum_zclassic_version_env.sh
- echo electrum-zclassic version is $ELECTRUM_ZCL_VERSION
- mkdir -p build && cp contrib/zclassic/travis/* ./build/
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      ./build/before_install-osx.sh;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then
      ./build/before_install-linux.sh;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then
      ./build/before_install-linux-apk.sh;
  fi
install:
- if [[ -z $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      pip install tox; pip install tox-travis;
  fi
script:
- if [[ -z $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]];then
      tox;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      ./build/travis-build-osx.sh ;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then
      ./build/travis-build-linux.sh;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then
      ./build/travis-build-linux-apk.sh;
  fi
deploy:
- provider: releases
  api_key:
    secure: qxlcqW7ViQq74zhWtz1QuOsVYVc0L1TklUrX3+y+bb6UQyve+71UD+MAt77VzW/14c/dKv0JROVYgIEeJq1m6k6vS54s9vlviIrZ6OQBsYudIKHAMaQEq3w+XD150X0MuiL0htR8okNCoeZMp+oVVYR4H+hXlwhbh14rUfMNjlMZ9tqlbqVNj51wRj7cp5+hZdvF/PrclduLx1PPUvXl5cfaxd+tvDxy6k+lzezKBdSP6T/+SX5QKICZclrnFiOjRYYbhWQDTAPFNG+Zydt2mcgqT0Cq7WDLZS2YciGgWOCe/hTl4BBA0QySckfTYwp9mpoOQ4mkDwWF9bCrOWRLSRDyIuLYAbKNTMdWYg/aqvOyobFtmEcs9COQpj4jum7zX33uOFGcNFhhi9S+cHLTMW+PPvEjBJgZ6g94pl4zxZ8Ak5i5iMuIHf3djEHV/quKIQARQ3+5mgBLjALMrT9Hzkj8ORHMO0zWfBVWs+No1TlkS0l4IdE5o0i2NiSBwjHZ7RCWjsXPMW8QkW/e1D0OAyHurudsHDDt5Xw8Z2tOtJitc7xeFNdZLHqc60fEJaBMOZrT1+/+fhOJTxwog4plwj2E4BOOJGMah2HAQLR5XNzHCU9mccoQdnGlAZUkdZpO8WLwMx5AHGyDJFKLG/Ws6Ai9i3CwDxfzzcNfeHH2w80=
  file:
  - build/electrum-zclassic/dist/electrum-zclassic-$ELECTRUM_ZCL_VERSION-macosx.dmg
  on:
    repo: hTrap/electrum-zclassic
    tags: true
    condition: "$TRAVIS_OS_NAME = osx"
- provider: releases
  api_key:
    secure: qxlcqW7ViQq74zhWtz1QuOsVYVc0L1TklUrX3+y+bb6UQyve+71UD+MAt77VzW/14c/dKv0JROVYgIEeJq1m6k6vS54s9vlviIrZ6OQBsYudIKHAMaQEq3w+XD150X0MuiL0htR8okNCoeZMp+oVVYR4H+hXlwhbh14rUfMNjlMZ9tqlbqVNj51wRj7cp5+hZdvF/PrclduLx1PPUvXl5cfaxd+tvDxy6k+lzezKBdSP6T/+SX5QKICZclrnFiOjRYYbhWQDTAPFNG+Zydt2mcgqT0Cq7WDLZS2YciGgWOCe/hTl4BBA0QySckfTYwp9mpoOQ4mkDwWF9bCrOWRLSRDyIuLYAbKNTMdWYg/aqvOyobFtmEcs9COQpj4jum7zX33uOFGcNFhhi9S+cHLTMW+PPvEjBJgZ6g94pl4zxZ8Ak5i5iMuIHf3djEHV/quKIQARQ3+5mgBLjALMrT9Hzkj8ORHMO0zWfBVWs+No1TlkS0l4IdE5o0i2NiSBwjHZ7RCWjsXPMW8QkW/e1D0OAyHurudsHDDt5Xw8Z2tOtJitc7xeFNdZLHqc60fEJaBMOZrT1+/+fhOJTxwog4plwj2E4BOOJGMah2HAQLR5XNzHCU9mccoQdnGlAZUkdZpO8WLwMx5AHGyDJFKLG/Ws6Ai9i3CwDxfzzcNfeHH2w80=
  file:
  - build/electrum-zclassic/dist/Electrum-Zclassic-$ELECTRUM_ZCL_VERSION.tar.gz
  - build/electrum-zclassic/dist/electrum-zclassic-$ELECTRUM_ZCL_VERSION-setup-win32.exe
  - build/electrum-zclassic/dist/electrum-zclassic-$ELECTRUM_ZCL_VERSION-setup-win64.exe
  - build/electrum-zclassic/bin/Electrum_Zclassic-$ELECTRUM_ZCL_APK_VERSION-release-unsigned.apk
  on:
    repo: hTrap/electrum-zclassic
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
